### ISSUE TITLE
使用keep-alive的时候出现bug

### ISSUE THREAD

**Issue by Elikke-007** [lhlyu/vue-virtual-waterfall#11]
我在首页展示瀑布流列表，想要在跳转到下一个路由之后保持页面状态，于是使用了 keep-alive 组件，
然后我遇到了问题，在使用导航返回到首页之后，页面只展示一个item。
我的代码如下：
`
<keep-alive include="waterFall">
      <router-view></router-view>
</keep-alive>
`
期待大佬的答复！谢谢！

**Comment by lhlyu** [comment]
我没有重现出来这种情况，你有例子的源码吗

**Comment by Elikke-007** [comment]
可以贴一下您的例子代码吗？我看看是哪里不同

**Comment by lhlyu** [comment]
- `App.vue`的代码
```
<router-view v-slot="{ Component, route }">
    <keep-alive>
        <component :is="Component" :key="route.name" />
    </keep-alive>
</router-view>
```
路由就两个页面一个是`Example.vue`，加了一个按钮跳转到`Other.vue`的页面，然后`Other.vue`有个按钮跳转到`Example.vue`

**Comment by Elikke-007** [comment]
我使用了 <keep-alive include="waterfall"></keep-alive>才出现问题，请问要怎么指定单独一个路由保持状态？因为其他页面我不需要保持，但是不指定路由的话，其他页面也保持了

**Comment by Elikke-007** [comment]
我的代码确实是错误的，使用`<keep-alive include="waterfall"></keep-alive>`报错了，请问要怎么指定单独一个路由保持状态？

**Comment by lhlyu** [comment]
我看了一下官方的定义:
```ts
interface KeepAliveProps {
  /**
   * 如果指定，则只有与 `include` 名称
   * 匹配的组件才会被缓存。
   */
  include?: MatchPattern
  /**
   * 任何名称与 `exclude`
   * 匹配的组件都不会被缓存。
   */
  exclude?: MatchPattern
  /**
   * 最多可以缓存多少组件实例。
   */
  max?: number | string
}
```

只要include指定组件的名字就好了，比如我的`Example.vue`的默认名字就是`Example`，然后向下面一样指定就好了

```vue
<router-view v-slot="{ Component, route }">
    <keep-alive include="Example">
        <component :is="Component" :key="route.name" />
    </keep-alive>
</router-view>
```

**Comment by Elikke-007** [comment]
感谢大佬耐心教导，谢谢！祝您生活愉快！

**Comment by Elikke-007** [comment]
我因为之前不小心把虚拟列表父容器的高度改成100%，以致于虚拟列表失效了，然后使用keep-alive组件的出现了问题，
后来发现并改成100vh之后就不会了。
