### ISSUE TITLE
itemWidth和itemMinWidth之间语义上有冲突？

### ISSUE THREAD

**Issue by Tindtily** [lhlyu/vue-virtual-waterfall#13]
实际代码中itemMinWidth只限于计算列数，不知道是有什么特殊考虑？

目前计算出的itemWidth明显小于itemMinWidth，所以从语义上看是有冲突的。

我现在做一个响应式页面，希望用固定宽度，目前看源码是不支持的。是否方便增加这样的支持？

**Comment by lhlyu** [comment]
itemWidth是当前列实际的宽度，itemMinWidth是列的最小宽度，因为我要优先保证`minColumnCount`的取值，所以有时候需要牺牲`itemMinWidth`。
我看你要实现响应式，固定宽度不好吧。

**Comment by Tindtily** [comment]
> itemWidth是当前列实际的宽度，itemMinWidth是列的最小宽度，因为我要优先保证`minColumnCount`的取值，所以有时候需要牺牲`itemMinWidth`。 我看你要实现响应式，固定宽度不好吧。

目前需求是固定宽度，只是不同尺寸的设备，用不同的列数。我已经在源码基础上改了一下。暂时满足需求了。

现在还有个问题就是我看你的demo里面监听滚动到底部是用的`requestAnimationFrame(checkScrollPosition)`，这样的话会一直执行这个函数。我对vue3不太熟悉，但是感觉这样的监听方式不是太好呢。

**Comment by lhlyu** [comment]
> > itemWidth是当前列实际的宽度，itemMinWidth是列的最小宽度，因为我要优先保证`minColumnCount`的取值，所以有时候需要牺牲`itemMinWidth`。 我看你要实现响应式，固定宽度不好吧。
> 
> 目前需求是固定宽度，只是不同尺寸的设备，用不同的列数。我已经在源码基础上改了一下。暂时满足需求了。
> 
> 现在还有个问题就是我看你的demo里面监听滚动到底部是用的`requestAnimationFrame(checkScrollPosition)`，这样的话会一直执行这个函数。我对vue3不太熟悉，但是感觉这样的监听方式不是太好呢。

除了不兼容低版本的浏览器，没其他问题

**Comment by lhlyu** [comment]
可以
