### ISSUE TITLE
已经加载过的图片，再次滚动到当前图片的位置还会重新加载

### ISSUE THREAD

**Issue by 80sky** [lhlyu/vue-virtual-waterfall#18]
请问大佬，已经加载过的图片，再次回到原来的图片位置不需要重新加载了应该怎么处理，比如我滚动到了第二屏，又回到了第一屏，发现第一屏的所有图片又重新loading了一次

**Comment by lhlyu** [comment]
浏览器第一次加载图片后会进行缓存，第二次是从内存或磁盘读取的
可以用个Set去记录已经加载过的图片(比如记录ID)，然后判断是否需要再次加载，我的例子里没有弄这个

**Comment by 80sky** [comment]
好的，谢谢大佬 我试下

**Comment by 80sky** [comment]
> 好的，谢谢大佬 我试下
