### ISSUE TITLE
有时间是否可以研究下支持一下ssr，nuxt这种框架

### ISSUE THREAD

**Issue by dxhuii** [lhlyu/vue-virtual-waterfall#5]
现在只支持client 客户端渲染。服务端渲染无法正常展示。

**Comment by lhlyu** [comment]
我试了可以使用
1. 先安装`@lhlyu/vue-virtual-waterfall`库
2. 你需要在`plugins`文件夹下创建一个`vue_virtual_waterfall.ts`文件，代码如下:
```ts
import VueVirtualWaterfall from '@lhlyu/vue-virtual-waterfall'
export default defineNuxtPlugin(nuxtApp => {
    nuxtApp.vueApp.use(VueVirtualWaterfall)
})
```

3. 然后直接使用就行了,示例代码:
```vue
<template>
    <VirtualWaterfall :items="data.items" :calcItemHeight="calcItemHeight" :loading="data.loading" ref="vw" @load-more="loadMoreData">
        <template #default="scope">
            <Card v-if="scope?.item" :cover="scope.item.img"></Card>
        </template>
    </VirtualWaterfall>
</template>
```

**Comment by dxhuii** [comment]
用是可以用，但ssr数据无法正常渲染。只有客户端的调用的接口数据才能正常渲染。

我写了一个示例，你看一下。https://stackblitz.com/edit/github-dnvvxy?file=pages%2Findex.vue

上面有普通渲染和你的组件渲染，同一份数据，普通渲染可以正常显示，但你的组件就无法展示内容了。你看下。

**Comment by lhlyu** [comment]
@dxhuii 我根据你的示例改了一下，[改后](https://stackblitz.com/edit/github-xnzza2?file=package.json)，
我发现你给的示例里用到了 `@vueuse/core`库，这个是专门给`vue`使用的，`nuxt`要用专门的`@vueuse/nuxt`,而且`@vueuse/nuxt`里的**hooks**比`@vueuse/core`的少，比如你直接使用了`import { useIntersectionObserver } from '@vueuse/core'`,这个在`nuxt`使用不了

**Comment by dxhuii** [comment]
![image](https://github.com/lhlyu/vue-virtual-waterfall/assets/2328917/65c15e8c-0d7b-4e10-8439-d5573dafd432)
我看了一下，现在还不是服务端渲染，如果是的话，HTML在查看源代码的时候，应该上面图片上HTML。
你发的示例是这样的
![image](https://github.com/lhlyu/vue-virtual-waterfall/assets/2328917/71e02d75-37f1-435b-b750-2cea39e347ae)
数据必须使用进入页面直接调用的数据。类似 这种的
```ts
const {
  data: datas,
  pending,
  error,
  refresh,
} = await useFetch('https://mock.tatakai.top/image/2/4');
```
但现在这样的调用的数据组组件，还是无法正常渲染。

**Comment by lhlyu** [comment]
确实有问题，我研究研究

**Comment by lhlyu** [comment]
@dxhuii 
我研究了一下，发现不行，因为我写的瀑布流需要知道dom容器的宽度，服务器渲染的时候不知道客户端需要多宽的容器，所以无法在服务端渲染，我这个瀑布流的库需要计算每个元素的位置，这都是需要客户端支持。其他方案的瀑布流可能可以做到，比如基于column布局的瀑布流

**Comment by lhlyu** [comment]
@dxhuii 
可以了，新版本`0.0.13`，这个是改后的[示例](https://stackblitz.com/edit/github-xnzza2)

**Comment by dxhuii** [comment]
嗯，好的，辛苦了。
