### ISSUE TITLE
下个阶段的改进

### ISSUE THREAD

**Issue by lhlyu** [lhlyu/vue-virtual-waterfall#6]
参考

- [动态生成DOM元素的高度及行数获取与计算方法](https://segmentfault.com/a/1190000004956121)

**Comment by lhlyu** [comment]
研究后发现对于本库而言，不可行！

**Comment by lhlyu** [comment]
### 参考

- [masonry](https://masonry.desandro.com/)
- [isotope](https://isotope.metafizzy.co/layout)

**Comment by lhlyu** [comment]
已解决:
```ts
// 计算真实高度，这里只计算除了图片的高度
function getRealHeight(item: ItemOption, realWidth: number) {
    const dom = document.createElement('div')

    render(
        h(Card, {
            item: item,
            width: realWidth + 'px',
            noImage: true
        }),
        dom
    )

    document.body.appendChild(dom)

    // 获取高度
    const height: number = dom.clientHeight

    // 移除新容器
    document.body.removeChild(dom)
    // 返回高度
    return height
}
```

**Comment by dxhuii** [comment]
现在支持，没有图片，纯文字的版本吗？图片和文字混合的

**Comment by lhlyu** [comment]
> 现在支持，没有图片，纯文字的版本吗？图片和文字混合的

支持了，可以看例子，我通过创建一个dom去计算文本的高度，再把dom删除，文本高度加上图片高度就可以了

**Comment by dxhuii** [comment]
嗯，好的，这个好，之前加个死的文字高度，只有一行文本的时候，空白区域太大。

只有文字的，我晚点试试。

我准备把有的内容，都关联到一个表里面，有图文的，有文字的。一起显示。

https://itrumors.com/buyers/xiaomi  现在部署了。  我这个也没有办法开源，好多内容没有弄上面来，等哪天完善了，再看要不要开源吧，现在设置为私有了。

内容还在加。现在用的 cf 有点卡。省掉了备案。

**Comment by dxhuii** [comment]
刚才改了下，发现
```ts
render(h(WaterfallText, { data: item }), dom)
```
这个方法不支持NuxtImg，找了半天原因，最终算是调好了。新建了一个 WaterfallText 没有图片，只有title的组件，用来给render方法调用，哈哈

顺便梳理了一下代码。用了你的方式 useWaterfall

**Comment by lhlyu** [comment]
@dxhuii 原生的img不行吗？
