### ISSUE TITLE
loadMoreData 一直再触发可能是什么原因呢？

### ISSUE THREAD

**Issue by Zhao-Michael** [lhlyu/vue-virtual-waterfall#7]

**Comment by lhlyu** [comment]
你可以把你示例代码共享出来吗，可以在这里发布出来 [https://stackblitz.com](https://stackblitz.com)

**Comment by Zhao-Michael** [comment]
不好意思，技术有点差，demo也没写出来
报错：Error in /~/src/components/HelloWorld.vue (22:52)
Cannot destructure property 'item' of 'undefined' as it is undefined.

https://stackblitz.com/edit/vue-vwfhem?file=src%2Fcomponents%2FHelloWorld.vue

**Comment by lhlyu** [comment]
@Zhao-Michael 修复了，更新到最新版本 `v0.0.14` 即可

**Comment by Zhao-Michael** [comment]
谢谢，等我有空试一下，目前我是用分页来绕过的

**Comment by Zhao-Michael** [comment]
Great Job!
