### ISSUE TITLE
是不支持绑定滚动父元素吗，比如我想把滚动绑在window上，整个页面就全局一个滚动（列表上面要banner）

### ISSUE THREAD

**Issue by wuyan1001** [lhlyu/vue-virtual-waterfall#8]

**Comment by lhlyu** [comment]
可以实现，但是改动会一点点大，跟现在的实现不兼容，可以作为下个版本的更新，这容器的部分交给使用者自己控制.
不过我暂时还没想清楚使用下面的哪种方案
1. 使用`vue`的内置组件`Teleport`，使用者可以指定挂载到目标容器下
2. 外层完全交给使用者，但内部是否还要保留监听向下滚动加载更多的事件，还是将事件完全交给使用者去实现

**Comment by dxhuii** [comment]
这个挺好，希望支持。

**Comment by lhlyu** [comment]
@dxhuii @wuyan1001 
可以了，新版本`1.0.0`，本次更新属于破坏性更新，不兼容老版本了，具体使用查看[文档](https://github.com/lhlyu/vue-virtual-waterfall/blob/main/README.zh.md)

**Comment by dxhuii** [comment]
今晚试下，最近有点懒，数据太少了，晚上还得再更新一下数据

**Comment by dxhuii** [comment]
已经使用了，好用，谢谢

**Comment by dxhuii** [comment]
@lhlyu 后面有时间可以加一个骨架屏 skeleton，这样下拉加载的时候，感觉好一点。

**Comment by lhlyu** [comment]
> @lhlyu 后面有时间可以加一个骨架屏 skeleton，这样下拉加载的时候，感觉好一点。
> 
  
em...例子不想写这么复杂，你是发现有什么问题吗？

**Comment by dxhuii** [comment]
> > @lhlyu 后面有时间可以加一个骨架屏 skeleton，这样下拉加载的时候，感觉好一点。
> 
> em...例子不想写这么复杂，你是发现有什么问题吗？

没有问题。
