### ISSUE TITLE
虚拟列表不生效

### ISSUE THREAD

**Issue by Elikke-007** [lhlyu/vue-virtual-waterfall#9]
我打开开发者工具查看 dom 节点发现只有向下滚动的时候，元素节点才会减少，但也不是 demo 中的效果。
我的元素节点数量达到 30 个左右，而且向上滚动，节点数量只会增加。
于是我下载了您的源码跑来看，又是正常的，然后逐一排查，发现您的 main.ts 中 app 是挂载到 body 中的，
然后我尝试修改成挂载到 body，结果是虚拟列表生效了。

提这个 issue 主要是想建议您可以在文档中添加这个说明。
最后，感谢大佬的贡献！

**Comment by lhlyu** [comment]
虚拟列表必须要保证包裹`VirtualWaterfall`组件的容器有固定的高度，比如下面代码中的`main`，必须指明固定高度:

```vue
<template>
  <main style="height: 500px">
    <VirtualWaterfall />
  </main>
</template>
```

我的例子里也固定了body的高度，代码在[这](https://github.com/lhlyu/vue-virtual-waterfall/blob/86c385866ef267525dfe0e762aa7e2f1dd9c95e9/src/example/useApp.ts#L7)
